#!/bin/bash
# Simple example to get started running a cuda program
#
# Load cuda command
module load CUDA 

# Compile the example
nvcc lanczos.cu -arch=compute_30 -code=sm_30 -I/mnt/home/manfred4/ViennaCL-1.7.1 -o adaptive_cuda

# Run the example on the command line
./adaptive_cuda

# Submit a cuda job to the queue
#qsub simple_cuda.qsub
