#!/bin/bash

#Compile 
g++ -o lanczos -lOpenCL -I/mnt/home/manfred4/ViennaCL-1.7.1 -DVIENNACL_WITH_OPENCL lanczos.cpp
#nvcc lanczosGPUCSR.cu -arch=compute_30 -code=sm_30 -I/mnt/home/manfred4/MatrixMarket -o lanczosGPUCSR_cuda

# Run 
./lanczos

